### ISSUE TITLE
Processing TMDB Data fails

### ISSUE THREAD

**Issue by antonbier** [RileyXX/TMDB-Trakt-Syncer#36]
### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Bug Description

Starting TMDBTraktSyncer....
Your settings are saved at:
/usr/lib/python3.12/site-packages/TMDBTraktSyncer
Processing Trakt Data
Processing Trakt Data Complete
Processing TMDB Data
   - Request failed with status code 401: This resource is private

--- ERROR ---
An error occurred while running the script.
Please submit the error to GitHub with the following information:
--------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/TMDBTraktSyncer/TMDBTraktSyncer.py", line 24, in main
    tmdb_watchlist, tmdb_ratings = tmdbData.getTMDBRatings()
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/TMDBTraktSyncer/tmdbData.py", line 24, in getTMDBRatings
    json_data = json.loads(response.text)
                           ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

### Environment

OS linux vm
Install method using pip

**Comment by RileyXX** [comment]
Hi sorry for the late reply. This issue should be fixed in the latest version v1.7.2. A problem was identified in another project where the script was improperly handling network errors such as error 54 connection reset by server (rate limiting). If you are still having problems with this let me know and I can reopen this issue. Thanks
